import "./globals.css";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import type { PropsWithChildren } from "react";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<PropsWithChildren>) {
	return (
		<html lang="en" className="">
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background`}>
				<div id="main-app" className="flex flex-col min-h-screen">
					<main className="flex-1">{children}</main>
					<footer>Footer</footer>
				</div>
			</body>
		</html>
	);
}
